//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using NDT.Infra.Data.Context;

//namespace NDT.Infra.Data.Migrations
//{
//    [DbContext(typeof(NdtDbContext))]
//    [Migration("20210209155443_add idenity")]
//    partial class addidenity
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "3.0.0")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .HasColumnType("nvarchar(256)")
//                        .HasMaxLength(256);

//                    b.Property<string>("NormalizedName")
//                        .HasColumnType("nvarchar(256)")
//                        .HasMaxLength(256);

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedName")
//                        .IsUnique()
//                        .HasName("RoleNameIndex")
//                        .HasFilter("[NormalizedName] IS NOT NULL");

//                    b.ToTable("AspNetRoles");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("RoleId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetRoleClaims");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<int>("AccessFailedCount")
//                        .HasColumnType("int");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Email")
//                        .HasColumnType("nvarchar(256)")
//                        .HasMaxLength(256);

//                    b.Property<bool>("EmailConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<bool>("LockoutEnabled")
//                        .HasColumnType("bit");

//                    b.Property<DateTimeOffset?>("LockoutEnd")
//                        .HasColumnType("datetimeoffset");

//                    b.Property<string>("NormalizedEmail")
//                        .HasColumnType("nvarchar(256)")
//                        .HasMaxLength(256);

//                    b.Property<string>("NormalizedUserName")
//                        .HasColumnType("nvarchar(256)")
//                        .HasMaxLength(256);

//                    b.Property<string>("PasswordHash")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PhoneNumber")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("PhoneNumberConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<string>("SecurityStamp")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("TwoFactorEnabled")
//                        .HasColumnType("bit");

//                    b.Property<string>("UserName")
//                        .HasColumnType("nvarchar(256)")
//                        .HasMaxLength(256);

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedEmail")
//                        .HasName("EmailIndex");

//                    b.HasIndex("NormalizedUserName")
//                        .IsUnique()
//                        .HasName("UserNameIndex")
//                        .HasFilter("[NormalizedUserName] IS NOT NULL");

//                    b.ToTable("AspNetUsers");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserClaims");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                {
//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("nvarchar(128)")
//                        .HasMaxLength(128);

//                    b.Property<string>("ProviderKey")
//                        .HasColumnType("nvarchar(128)")
//                        .HasMaxLength(128);

//                    b.Property<string>("ProviderDisplayName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("LoginProvider", "ProviderKey");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserLogins");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                {
//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("RoleId")
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("UserId", "RoleId");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetUserRoles");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                {
//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("nvarchar(128)")
//                        .HasMaxLength(128);

//                    b.Property<string>("Name")
//                        .HasColumnType("nvarchar(128)")
//                        .HasMaxLength(128);

//                    b.Property<string>("Value")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("UserId", "LoginProvider", "Name");

//                    b.ToTable("AspNetUserTokens");
//                });

//            modelBuilder.Entity("NDT.Domain.Models.Client", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Address")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("CentralFaxNo")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("CentralPhoneNo")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("CeoName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClientName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("EmailAddress")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("JobDomain")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("SiteFaxNo")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("SitePhoneNo")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("Clients");

//                    b.HasData(
//                        new
//                        {
//                            Id = new Guid("a30b169d-9255-4420-9160-e68635fa43f6"),
//                            Address = "تهران- خیابان ولی عصر خیابان بهرامی پلاک50",
//                            CeoName = "احمد محمدی",
//                            ClientName = " صنایع  پتروشیمی رامپکو"
//                        },
//                        new
//                        {
//                            Id = new Guid("c33a2536-ac30-4b7a-9a85-ef32e3c1d5f3"),
//                            Address = "اراک-کوی صنعتی ,خیابان پامچال ",
//                            CeoName = "علی حمیدی",
//                            ClientName = "ماشین سازی اراک"
//                        },
//                        new
//                        {
//                            Id = new Guid("6fd77f45-38a3-409d-967f-35361b139a0d"),
//                            Address = "قشم-مجتمع خلیج فارس -واحد 84",
//                            CeoName = "حسین نوابی",
//                            ClientName = "فراپتروسازان انرژی قشم"
//                        });
//                });

//            modelBuilder.Entity("NDT.Domain.Models.MenuModel", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("ActionName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClassIcon")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ControllerName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<Guid?>("ParentId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Title")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("MenuModel");

//                    b.HasData(
//                        new
//                        {
//                            Id = new Guid("4abe6fb7-a4f9-42d7-b62f-eba32bab705b"),
//                            ActionName = "ShowClients",
//                            ControllerName = "Client",
//                            Title = "کارفرمایان"
//                        },
//                        new
//                        {
//                            Id = new Guid("607dd871-ebda-48e7-9bd0-690fa42fe279"),
//                            ActionName = "Details",
//                            ControllerName = "Project",
//                            Title = "پروژه‌ها"
//                        },
//                        new
//                        {
//                            Id = new Guid("4b1c0e96-772d-4cf3-9fe7-c7e492e09056"),
//                            ActionName = "",
//                            ControllerName = "",
//                            Title = "تجهیزات"
//                        },
//                        new
//                        {
//                            Id = new Guid("d98ec621-9340-4af5-b1b2-f1d52775ba25"),
//                            ActionName = "",
//                            ControllerName = "",
//                            Title = "دستگاه‌ها"
//                        });
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
