// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NDT.Infra.Data.Context;

namespace NDT.Infra.Data.Migrations
{
    [DbContext(typeof(NdtDbContext))]
    [Migration("20210127084258_SeedClient")]
    partial class SeedClient
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NDT.Domain.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CentralFaxNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CentralPhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CeoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobDomain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteFaxNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SitePhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("236edf90-3840-4b4a-942b-f96db920458c"),
                            Address = "تهران- خیابان ولی عصر خیابان بهرامی پلاک50",
                            CeoName = "احمد محمدی",
                            ClientName = " صنایع  پتروشیمی رامپکو"
                        },
                        new
                        {
                            Id = new Guid("91d25ba0-25ed-49b3-ad43-9b5d604160b4"),
                            Address = "اراک-کوی صنعتی ,خیابان پامچال ",
                            CeoName = "علی حمیدی",
                            ClientName = "ماشین سازی اراک"
                        },
                        new
                        {
                            Id = new Guid("649b6b3c-b052-4c44-820c-fb973d4dcee4"),
                            Address = "قشم-مجتمع خلیج فارس -واحد 84",
                            CeoName = "حسین نوابی",
                            ClientName = "فراپتروسازان انرژی قشم"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
