// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NDT.Infra.Data.Context;

namespace NDT.Infra.Data.Migrations
{
    [DbContext(typeof(NdtDbContext))]
    [Migration("20210208111744_insert menuitem")]
    partial class insertmenuitem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NDT.Domain.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CentralFaxNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CentralPhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CeoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobDomain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteFaxNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SitePhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e6ad597-74a4-4357-abed-60012f926a95"),
                            Address = "تهران- خیابان ولی عصر خیابان بهرامی پلاک50",
                            CeoName = "احمد محمدی",
                            ClientName = " صنایع  پتروشیمی رامپکو"
                        },
                        new
                        {
                            Id = new Guid("8e78cf78-0e3a-4e53-97a2-55e6f7816f44"),
                            Address = "اراک-کوی صنعتی ,خیابان پامچال ",
                            CeoName = "علی حمیدی",
                            ClientName = "ماشین سازی اراک"
                        },
                        new
                        {
                            Id = new Guid("b03fd78b-f5a7-42a8-a1ec-b1216fb866cc"),
                            Address = "قشم-مجتمع خلیج فارس -واحد 84",
                            CeoName = "حسین نوابی",
                            ClientName = "فراپتروسازان انرژی قشم"
                        });
                });

            modelBuilder.Entity("NDT.Domain.Models.MenuModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuModel");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3006cc5e-8925-4a92-aa7f-df914454b58c"),
                            ActionName = "ShowClients",
                            ControllerName = "Client",
                            Title = "کارفرمایان"
                        },
                        new
                        {
                            Id = new Guid("c200e711-de69-4853-bebc-02ab45e8ff3e"),
                            ActionName = "Details",
                            ControllerName = "Project",
                            Title = "پروژه‌ها"
                        },
                        new
                        {
                            Id = new Guid("39072b84-ac42-4fff-aac3-60bc06aa001e"),
                            ActionName = "",
                            ControllerName = "",
                            Title = "تجهیزات"
                        },
                        new
                        {
                            Id = new Guid("b4ba5589-58b1-4365-b6dd-cc1dced86cc8"),
                            ActionName = "",
                            ControllerName = "",
                            Title = "دستگاه‌ها"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
